# Generated by Django 5.2.8 on 2025-11-20 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=512)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Add_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_preview', models.FileField(blank=True, null=True, upload_to='movies_images')),
                ('movies_preview_url', models.CharField(blank=True, max_length=5024, null=True)),
                ('movies_name', models.CharField(max_length=128)),
                ('movies_description', models.CharField(max_length=2048)),
                ('movies_url', models.CharField(blank=True, max_length=10000000, null=True)),
                ('movies_local', models.FileField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('year', models.CharField(default='', max_length=32)),
                ('genre', models.CharField(default='', max_length=512)),
                ('all_series', models.CharField(default='', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_possible', models.BooleanField(default=False)),
                ('add_departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_departments', to='add_all.add_departments')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comments', to='add_all.add_movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('video_url', models.CharField(max_length=2048)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='add_all.add_movies')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('read_by_ips', models.JSONField(blank=True, default=list)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='SavedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_all.add_movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_all.add_movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'unique_together': {('ip_address', 'movie'), ('session_key', 'movie'), ('user', 'movie')},
            },
        ),
    ]
